/**
 * Platform Skills Registry
 *
 * Loads platform-specific cheatsheets for the extension AI agent.
 * Skills can be:
 * 1. Static (checked into code, like x-ads.ts)
 * 2. Dynamic (generated/updated by the skill generator and stored in DB or file)
 *
 * The system checks for a dynamic skill first (more recent), falls back to static.
 */

import { readFile, readdir } from "fs/promises";
import { join } from "path";

const DYNAMIC_SKILLS_DIR = join(process.cwd(), ".extension-skills");

// Static skills as fallback — only used if no dynamic .md file exists
let _staticSkillCache: Record<string, string> | null = null;

async function loadStaticSkills(): Promise<Record<string, string>> {
  if (_staticSkillCache) return _staticSkillCache;
  _staticSkillCache = {};
  try {
    // Dynamically import any static .ts skill files
    const { X_ADS_SKILL } = await import("./x-ads");
    _staticSkillCache["x"] = X_ADS_SKILL;
  } catch { /* no static skills */ }
  return _staticSkillCache;
}

/**
 * Get the skill for a platform.
 * Priority: dynamic (.md file from generator) > static (.ts file in code)
 */
export async function getPlatformSkill(platform: string): Promise<string> {
  // Try dynamic skill first (generated by admin tool)
  try {
    const dynamicPath = join(DYNAMIC_SKILLS_DIR, `${platform}.md`);
    const content = await readFile(dynamicPath, "utf-8");
    if (content.trim().length > 100) {
      return content;
    }
  } catch {
    // No dynamic skill
  }

  // Fall back to static
  const statics = await loadStaticSkills();
  return statics[platform] || "";
}

/**
 * List all available platform skills (static + dynamic).
 */
export async function listPlatforms(): Promise<string[]> {
  const statics = Object.keys(await loadStaticSkills());
  const dynamics: string[] = [];
  try {
    const files = await readdir(DYNAMIC_SKILLS_DIR);
    dynamics.push(...files.filter(f => f.endsWith(".md")).map(f => f.replace(".md", "")));
  } catch { /* no dir */ }
  return [...new Set([...statics, ...dynamics])];
}
